### ISSUE TITLE
Importing existent accounts

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/emerald-cli#29]
If I understood correctly `emerald import` command would replace existent key data for address if such address already in vault. It can lead to situation when user accidentally replace working keys with another key, encrypted by another passphrase.

As a solution we can introduce additional parameters:
`-f` - force to replace existent keys. User must explicitly ask to replace. 
`-i` - ignore existent keys. This is safe option. 

What do you think ?

**Comment by r8d8** [comment]
We not prohibiting replacement for exisitng aacount because of  `update` command.
Maybe, we should add `-f` option, but skip `-i` as it's will be default behaviour

**Comment by gagarin55** [comment]
So, import command doesn't replace existent ? if so we can leave it as is but update documentation
